//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xiaolu.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public string Description { get; set; }
        public bool Gender { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public int Level { get; set; }
        public int Status { get; set; }
        public string Mobile { get; set; }
        public bool IsLocked { get; set; }
        public Nullable<System.DateTime> LoginTime { get; set; }
        public string LoginAddress { get; set; }
        public string LoginLang { get; set; }
        public Nullable<int> ErrLoginTimes { get; set; }
        public Nullable<System.DateTime> LastFailLoginTime { get; set; }
        public Nullable<System.DateTime> LastResetPasswordTime { get; set; }
        public string WeixinId { get; set; }
    }
}
