//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xiaolu.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<bool> gender { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public Nullable<bool> level { get; set; }
        public string xiaolu_usercol { get; set; }
    }
}
